# Generated by Django 4.1.4 on 2022-12-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('three', models.IntegerField()),
                ('four', models.IntegerField()),
                ('five', models.IntegerField()),
                ('six', models.IntegerField()),
                ('seven', models.IntegerField()),
                ('eight', models.IntegerField()),
                ('nine', models.IntegerField()),
                ('ten', models.IntegerField()),
                ('eleven', models.IntegerField()),
                ('twelve', models.IntegerField()),
                ('thirteen', models.IntegerField()),
                ('fourteen', models.IntegerField()),
                ('fifteen', models.IntegerField()),
                ('sixteen', models.IntegerField()),
                ('seventeen', models.IntegerField()),
                ('eighteen', models.IntegerField()),
                ('nineteen', models.IntegerField()),
                ('twenty', models.IntegerField()),
                ('twentyone', models.IntegerField()),
                ('twentytwo', models.IntegerField()),
                ('twentythree', models.IntegerField()),
                ('twentyfour', models.CharField(max_length=100)),
                ('twentyfive', models.CharField(max_length=100)),
            ],
        ),
    ]
