# Generated by Django 4.1.4 on 2022-12-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Data',
        ),
    ]
